language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
#Command to run tests
script:
   - pytest
   - pytest --cov=.
after_success:
  - coveralls 
  
 
